[project]
name = "kestra-runtime"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-bigquery>=1.9.0",
    "dbt-coves>=1.8.13",
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
]
